$: << File.expand_path(File.dirname(__FILE__) + "/../lib")
require 'coyote/rake'

coyote :build do |config|
  config.input = "scripts.js"
  config.output = "output.js"
end

coyote :watch do |config|
  config.input = "scripts.js"
  config.output = "output.js"
end
