require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('coyote', '0.2.0') do |p|
  p.description    = "A command-line gem to combine multiple files"
  p.url            = "http://github.com/caseyohara/coyote"
  p.author         = "Casey O'Hara"
  p.email          = "casey.ohara@imulus.com"
  p.ignore_pattern = ["tmp/*", "script/*"]
  p.development_dependencies = ["closure-compiler >=1.1.1"]
	p.runtime_dependencies = ["closure-compiler >=1.1.1"]
end